apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: myapp-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: my-springboot-app
  unhealthyPodEvictionPolicy: AlwaysAllow
