apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-app
  labels:
    app: my-springboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-springboot-app
  template:
    metadata:
      labels:
        app: my-springboot-app
    spec:
      containers:
        - name: my-springboot-app
          image: {{ .Values.springboot.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/{{ .Values.mysql.database }}
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.mysql.rootPassword }}
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "500Mi"
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "250Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            readOnlyRootFilesystem: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - my-springboot-app
            topologyKey: "kubernetes.io/hostname"
